-- F-ChatBouncer backend – PostgreSQL schema (fresh deploy)
-- Generated from EF Core migrations (idempotent). Safe to run on an empty database
-- or one that already has some migrations applied.
--
-- Prerequisites:
--   - PostgreSQL database created (e.g. createdb fchat_bouncer)
--   - Connection configured via DATABASE_URL or PGHOST/PGPORT/PGDATABASE/PGUSER/PGPASSWORD
--
-- Run:
--   psql "$DATABASE_URL" -f scripts/deploy-fresh-database.sql
--   or: psql -h localhost -U postgres -d fchat_bouncer -f scripts/deploy-fresh-database.sql
--

CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE TABLE "Channels" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "FChatChannelName" character varying(100) NOT NULL,
        "DisplayName" character varying(100),
        "Subscribed" boolean NOT NULL,
        "JoinedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Channels" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Channels_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE TABLE "Messages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ChannelName" character varying(100) NOT NULL,
        "MessageType" integer NOT NULL,
        "Sender" character varying(50) NOT NULL,
        "Content" text NOT NULL,
        "Timestamp" timestamp with time zone NOT NULL,
        "FChatMessageId" character varying(100),
        CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Messages_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE TABLE "UserSessions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "FChatSessionId" character varying(100),
        "Status" integer NOT NULL,
        "ConnectedAt" timestamp with time zone NOT NULL,
        "LastActivity" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UserSessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_UserSessions_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE TABLE "UserSettings" (
        "UserId" text NOT NULL,
        "RetentionDays" integer NOT NULL,
        "AutoPurgeEnabled" boolean NOT NULL,
        "FChatCredentialsEncrypted" text,
        "LastPurge" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UserSettings" PRIMARY KEY ("UserId"),
        CONSTRAINT "FK_UserSettings_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Channels_User_FChatChannel_Unique" ON "Channels" ("UserId", "FChatChannelName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE INDEX "IX_Messages_Timestamp" ON "Messages" ("Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE INDEX "IX_Messages_User_Channel_Timestamp" ON "Messages" ("UserId", "ChannelName", "Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE INDEX "IX_Messages_User_Timestamp" ON "Messages" ("UserId", "Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    CREATE INDEX "IX_UserSessions_UserId" ON "UserSessions" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250918161842_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250918161842_InitialCreate', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922020949_AddQueuedMessages') THEN
    CREATE TABLE "QueuedMessages" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ChannelName" character varying(100) NOT NULL,
        "SenderCharacter" character varying(50) NOT NULL,
        "Content" text NOT NULL,
        "MessageType" integer NOT NULL,
        "QueuedAt" timestamp with time zone NOT NULL,
        "RetryCount" integer NOT NULL,
        "LastAttempt" timestamp with time zone,
        CONSTRAINT "PK_QueuedMessages" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_QueuedMessages_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922020949_AddQueuedMessages') THEN
    CREATE INDEX "IX_QueuedMessages_UserId" ON "QueuedMessages" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922020949_AddQueuedMessages') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250922020949_AddQueuedMessages', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922115732_UpdateProfileStructure') THEN
    CREATE TABLE "Profiles" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "CharacterName" character varying(100) NOT NULL,
        "ProfileData" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        "RawProData" text,
        CONSTRAINT "PK_Profiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Profiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922115732_UpdateProfileStructure') THEN
    CREATE INDEX "IX_Profiles_UserId" ON "Profiles" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922115732_UpdateProfileStructure') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250922115732_UpdateProfileStructure', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922144109_AddCharacterConnections') THEN
    CREATE TABLE "CharacterConnections" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" character varying(450) NOT NULL,
        "CharacterName" character varying(100) NOT NULL,
        "FChatUsername" character varying(100) NOT NULL,
        "FChatPasswordEncrypted" character varying(500) NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsConnected" boolean NOT NULL,
        "ConnectedAt" timestamp with time zone NOT NULL,
        "LastActivityAt" timestamp with time zone NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CharacterConnections" PRIMARY KEY ("Id"),
        CONSTRAINT "AK_CharacterConnections_UserId_CharacterName" UNIQUE ("UserId", "CharacterName"),
        CONSTRAINT "FK_CharacterConnections_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922144109_AddCharacterConnections') THEN
    CREATE TABLE "CharacterChannels" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" character varying(450) NOT NULL,
        "CharacterName" character varying(100) NOT NULL,
        "ChannelId" character varying(100) NOT NULL,
        "JoinedAt" timestamp with time zone NOT NULL,
        "LastActivityAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CharacterChannels" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CharacterChannels_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CharacterChannels_CharacterConnections_UserId_CharacterName" FOREIGN KEY ("UserId", "CharacterName") REFERENCES "CharacterConnections" ("UserId", "CharacterName") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922144109_AddCharacterConnections') THEN
    CREATE UNIQUE INDEX "IX_CharacterChannels_User_Character_Channel_Unique" ON "CharacterChannels" ("UserId", "CharacterName", "ChannelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922144109_AddCharacterConnections') THEN
    CREATE UNIQUE INDEX "IX_CharacterConnections_User_Character_Unique" ON "CharacterConnections" ("UserId", "CharacterName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922144109_AddCharacterConnections') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250922144109_AddCharacterConnections', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922201040_AddCharacterNameToMessage') THEN
    ALTER TABLE "Messages" ADD "CharacterName" character varying(50) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922201040_AddCharacterNameToMessage') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250922201040_AddCharacterNameToMessage', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterChannels" DROP CONSTRAINT "FK_CharacterChannels_AspNetUsers_UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterChannels" DROP CONSTRAINT "FK_CharacterChannels_CharacterConnections_UserId_CharacterName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterConnections" DROP CONSTRAINT "AK_CharacterConnections_UserId_CharacterName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    DROP INDEX "IX_CharacterConnections_User_Character_Unique";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    DROP INDEX "IX_CharacterChannels_User_Character_Channel_Unique";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterConnections" ADD "CharacterId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterChannels" ADD "BouncerUserId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterChannels" ADD "CharacterConnectionId" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterChannels" ADD "CharacterId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    CREATE TABLE "Characters" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "Status" character varying(50) NOT NULL,
        "StatusMessage" character varying(500),
        "Gender" character varying(50) NOT NULL,
        "LastSeen" timestamp with time zone NOT NULL,
        "FirstSeen" timestamp with time zone NOT NULL,
        "LastUpdated" timestamp with time zone NOT NULL,
        "ProfileData" text,
        "StructuredProfileData" text,
        "RawProData" text,
        "IsOnline" boolean NOT NULL,
        CONSTRAINT "PK_Characters" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    CREATE INDEX "IX_CharacterConnections_CharacterId" ON "CharacterConnections" ("CharacterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    CREATE INDEX "IX_CharacterConnections_IsActive" ON "CharacterConnections" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    CREATE INDEX "IX_CharacterConnections_IsConnected" ON "CharacterConnections" ("IsConnected");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    CREATE UNIQUE INDEX "IX_CharacterConnections_User_Character_Unique" ON "CharacterConnections" ("UserId", "CharacterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    CREATE INDEX "IX_CharacterChannels_BouncerUserId" ON "CharacterChannels" ("BouncerUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    CREATE INDEX "IX_CharacterChannels_CharacterId" ON "CharacterChannels" ("CharacterId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    CREATE UNIQUE INDEX "IX_CharacterChannels_Connection_Channel_Unique" ON "CharacterChannels" ("CharacterConnectionId", "ChannelId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    CREATE INDEX "IX_Characters_IsOnline" ON "Characters" ("IsOnline");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    CREATE UNIQUE INDEX "IX_Characters_Name_Unique" ON "Characters" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    CREATE INDEX "IX_Characters_Status" ON "Characters" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN

                    INSERT INTO "Characters" ("Name", "Status", "StatusMessage", "Gender", "LastSeen", "FirstSeen", "LastUpdated", "IsOnline")
                    SELECT DISTINCT 
                        "CharacterName",
                        'offline' as "Status",
                        NULL as "StatusMessage",
                        'None' as "Gender",
                        NOW() as "LastSeen",
                        NOW() as "FirstSeen",
                        NOW() as "LastUpdated",
                        false as "IsOnline"
                    FROM "CharacterConnections"
                    WHERE "CharacterName" IS NOT NULL AND "CharacterName" != '';

    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN

                    UPDATE "CharacterConnections"
                    SET "CharacterId" = c."Id"
                    FROM "Characters" c
                    WHERE "CharacterConnections"."CharacterName" = c."Name";

    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterConnections" ALTER COLUMN "CharacterId" SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterConnections" DROP COLUMN "CharacterName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterChannels" DROP COLUMN "CharacterName";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterChannels" DROP COLUMN "UserId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterChannels" ADD CONSTRAINT "FK_CharacterChannels_AspNetUsers_BouncerUserId" FOREIGN KEY ("BouncerUserId") REFERENCES "AspNetUsers" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterChannels" ADD CONSTRAINT "FK_CharacterChannels_CharacterConnections_CharacterConnectionId" FOREIGN KEY ("CharacterConnectionId") REFERENCES "CharacterConnections" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterChannels" ADD CONSTRAINT "FK_CharacterChannels_Characters_CharacterId" FOREIGN KEY ("CharacterId") REFERENCES "Characters" ("Id");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    ALTER TABLE "CharacterConnections" ADD CONSTRAINT "FK_CharacterConnections_Characters_CharacterId" FOREIGN KEY ("CharacterId") REFERENCES "Characters" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250923163505_UnifiedCharacterModel') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250923163505_UnifiedCharacterModel', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924124745_AddGoogleOAuthAndSecurityFields') THEN
    ALTER TABLE "AspNetUsers" ADD "FailedLoginAttempts" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924124745_AddGoogleOAuthAndSecurityFields') THEN
    ALTER TABLE "AspNetUsers" ADD "GoogleEmail" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924124745_AddGoogleOAuthAndSecurityFields') THEN
    ALTER TABLE "AspNetUsers" ADD "GoogleId" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924124745_AddGoogleOAuthAndSecurityFields') THEN
    ALTER TABLE "AspNetUsers" ADD "GoogleName" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924124745_AddGoogleOAuthAndSecurityFields') THEN
    ALTER TABLE "AspNetUsers" ADD "GooglePicture" text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924124745_AddGoogleOAuthAndSecurityFields') THEN
    ALTER TABLE "AspNetUsers" ADD "HasFChatCredentials" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924124745_AddGoogleOAuthAndSecurityFields') THEN
    ALTER TABLE "AspNetUsers" ADD "LastFChatCredentialsUpdate" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924124745_AddGoogleOAuthAndSecurityFields') THEN
    ALTER TABLE "AspNetUsers" ADD "LastLoginAt" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924124745_AddGoogleOAuthAndSecurityFields') THEN
    ALTER TABLE "AspNetUsers" ADD "LastPasswordChange" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250924124745_AddGoogleOAuthAndSecurityFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250924124745_AddGoogleOAuthAndSecurityFields', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250926130507_AddMemoFields') THEN
    ALTER TABLE "Characters" ADD "Memo" character varying(1000);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250926130507_AddMemoFields') THEN
    ALTER TABLE "Characters" ADD "MemoLastUpdated" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250926130507_AddMemoFields') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250926130507_AddMemoFields', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010143850_AddProfileQueueItem') THEN
    CREATE TABLE "ProfileQueueItems" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" character varying(450) NOT NULL,
        "CharacterName" character varying(100) NOT NULL,
        "RequestedAt" timestamp with time zone NOT NULL,
        "ProcessedAt" timestamp with time zone,
        "RequestType" integer NOT NULL,
        "Priority" integer NOT NULL,
        "RetryCount" integer NOT NULL,
        "MaxRetries" integer NOT NULL,
        "ErrorMessage" text,
        "Status" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ProfileQueueItems" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010143850_AddProfileQueueItem') THEN
    CREATE INDEX "IX_ProfileQueueItems_Status_Priority_Requested" ON "ProfileQueueItems" ("Status", "Priority", "RequestedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010143850_AddProfileQueueItem') THEN
    CREATE INDEX "IX_ProfileQueueItems_UpdatedAt" ON "ProfileQueueItems" ("UpdatedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010143850_AddProfileQueueItem') THEN
    CREATE INDEX "IX_ProfileQueueItems_User_Character_Status" ON "ProfileQueueItems" ("UserId", "CharacterName", "Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251010143850_AddProfileQueueItem') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251010143850_AddProfileQueueItem', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111225211_RemoveProfileTable') THEN
    DROP TABLE "Profiles";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251111225211_RemoveProfileTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251111225211_RemoveProfileTable', '9.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251112164804_AddAuditLog') THEN
    CREATE TABLE "AuditLogs" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text,
        "EventType" character varying(50) NOT NULL,
        "EventCategory" character varying(50) NOT NULL,
        "Action" character varying(500) NOT NULL,
        "ResourceType" character varying(50),
        "ResourceId" character varying(100),
        "IpAddress" character varying(45) NOT NULL,
        "UserAgent" character varying(500),
        "Success" boolean NOT NULL,
        "FailureReason" character varying(500),
        "Metadata" text,
        "CorrelationId" character varying(36),
        "Timestamp" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AuditLogs_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251112164804_AddAuditLog') THEN
    CREATE INDEX "IX_AuditLogs_CorrelationId" ON "AuditLogs" ("CorrelationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251112164804_AddAuditLog') THEN
    CREATE INDEX "IX_AuditLogs_EventType_Timestamp" ON "AuditLogs" ("EventType", "Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251112164804_AddAuditLog') THEN
    CREATE INDEX "IX_AuditLogs_Timestamp" ON "AuditLogs" ("Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251112164804_AddAuditLog') THEN
    CREATE INDEX "IX_AuditLogs_User_Timestamp" ON "AuditLogs" ("UserId", "Timestamp");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251112164804_AddAuditLog') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251112164804_AddAuditLog', '9.0.0');
    END IF;
END $EF$;
COMMIT;
